[package]
name = "driver-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.1"
once_cell = "1.18.0"
process_path = "0.1.4"
thiserror = "1.0.50"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"

cppvtbl = "0.2.1"
real_c_string = "1.0.1"

valve-pm = { path = "../../crates/valve-pm" }
vive-hid = { path = "../../crates/vive-hid" }
lens-client = { path = "../../crates/lens-client" }
lens-protocol = { path = "../../crates/lens-protocol" }
openvr = { path = "../../crates/openvr" }
tokio = { version = "1.34.0", features = ["rt", "rt-multi-thread"] }

[lib]
crate-type = ["cdylib"]
