[package]
name = "lens-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lens-protocol = { path = "../../crates/lens-protocol" }
libloading = "0.7.3"
process_path = "0.1.3"
tracing-subscriber = "0.3.9"
tracing = "0.1.31"
anyhow = "1.0"
serde_json = "1.0"
