[package]
name = "lens-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lens-protocol = { path = "../../crates/lens-protocol" }
libloading = "0.8.1"
process_path = "0.1.4"
tracing-subscriber = "0.3.17"
tracing = "0.1.40"
anyhow = "1.0"
serde_json = "1.0"
